CREATE TABLE pacientes (

   id BIGINT AUTO_INCREMENT NOT NULL,
   nome VARCHAR(100) NOT NULL,
   email VARCHAR(100) NOT NULL,
   telefone VARCHAR(20) NOT NULL,
   cpf VARCHAR(20) NOT NULL,
   logradouro VARCHAR(100) NOT NULL,
   numero VARCHAR(20) NULL,
   complemento VARCHAR(100) NULL,
   bairro VARCHAR(100) NOT NULL,
   cidade VARCHAR(100) NOT NULL,
   cep VARCHAR(8) NOT NULL,
   uf VARCHAR(2) NOT NULL,

   PRIMARY KEY (id)

);